name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master','cartoonspace']

env:
  IMAGE: "${{ secrets.DOCKER_USER }}/${{secrets.DOCKER_REPO}}"
  TAG: "latest"

jobs:
  docker-slim:
    strategy:
      matrix:
        overwrite: [true, false]
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repo: ${{secrets.DOCKER_REPO}}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{secrets.DOCKER_REPO}}:latest
      

      - name: Before
        run: docker image ls "${{ env.IMAGE }}:${{ env.TAG }}"

      - name: docker-slim
        uses: kitabisa/docker-slim-action@master
        id: slim
        env:
          DSLIM_HTTP_PROBE: true
        with:
          target: ${{ env.IMAGE }}:latest
          overwrite: ${{ matrix.overwrite }}

      - name: After
        run: docker image ls "${{ env.IMAGE }}"

      - name: Report
        env:
          REPORT: ${{ steps.slim.outputs.report }} # report is JSON format
        run: echo "${REPORT}"
